_BASE_: ../Base.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]
  AUGMIX:
    ENABLED: True
    PROB : 0.0

DATASETS:
  NAMES: ("VeRiUAV",)
  TESTS: ("VeRiUAV",)

DATALOADER:
  SAMPLER_TRAIN: BalancedIdentitySampler

MODEL:
  BACKBONE:
    WITH_IBN: False 

SOLVER:
  OPT: SGD
  BASE_LR: 0.000035
  ETA_MIN_LR: 7.7e-5

  IMS_PER_BATCH: 32 #64
  MAX_EPOCH: 60
  WARMUP_ITERS: 3000
  FREEZE_ITERS: 3000

  CHECKPOINT_PERIOD: 10

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128

OUTPUT_DIR: logs/VeRi-UAV-orig1
