MODEL:
  META_ARCHITECTURE: Baseline

  BACKBONE:
    NAME: build_resnet_backbone
    NORM: BN 
    DEPTH: 50x   
    LAST_STRIDE: 1
    FEAT_DIM: 2048  
    WITH_IBN: False
    PRETRAIN: True

  HEADS:
    NAME: EmbeddingHead
    NORM: BN 
    WITH_BNNECK: True
    POOL_LAYER: GlobalAvgPool
    NECK_FEAT: before
    CLS_LAYER: Linear

  LOSSES:
    NAME: ("CrossEntropyLoss","TripletLoss")

    CE:
      EPSILON: 0.1
      SCALE: 1.

    TRI:
      MARGIN: 0.0
      HARD_MINING: False
      NORM_FEAT: False
      SCALE: 1.0

    SUPCON:
      SCALE: 0.5 
    
INPUT:
  SIZE_TRAIN: [ 256, 128 ]
  SIZE_TEST: [ 256, 128 ]
  AUTOAUG:
    ENABLED: True
    PROB: 0.1
  REA:
    ENABLED: True 
    PROB: 0.5

  FLIP:
    ENABLED: True 

  PADDING:
    ENABLED: True
    

DATALOADER:
  SAMPLER_TRAIN: NaiveIdentitySampler
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  AMP:
    ENABLED: True
  OPT: Adam
  MAX_EPOCH: 120
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_NORM: 0.0005
  IMS_PER_BATCH: 64

  SCHED: MultiStepLR
  STEPS: [ 30,50, ]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 2000

  CHECKPOINT_PERIOD: 30

TEST:
  EVAL_PERIOD: 30
  IMS_PER_BATCH: 128

CUDNN_BENCHMARK: True
